name: Deploy to EC2

on:
    push:
      branches:
        - main


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Check out the repository
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME}}
            password: ${{ secrets.DOCKER_PASSWORD}}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: agarwalprashant355/node-example-1:2.0

        - name: Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
                host: ${{ secrets.EC2_HOST }}:22
                username: ec2-user
                key: ${{ secrets.SSH_KEY }}
                script: |
                    docker stop dabbu || true
                    docker run -d --rm -p 80:80 --name dabbu agarwalprashant355/node-example-1:2.0